version: '3'
services:
  server:
    command: bash -c "npm run server"
    build: .
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    depends_on:
      - postgres
    links:
      - postgres

  client:
    command: bash -c "npm run client"
    build: .
    ports:
      - "3000:3000"

  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
