version: '3'
services:
  cmegestao:
    container_name: cmegestao
    build: .
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres